language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - business@mircogatz.de
    on_success: change
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
